import os

filepath = r'C:\Users\Administrator\Documents\Codex\2026-07-08\workspace-codex-workspace-sop-sop\workspace-root\foldcraft\src\pages\Projects.jsx'

L = []
a = L.append
a('import { useState } from "react"')
a('import { Menu, X, ArrowRight, Globe, Waves, Fish, Anchor, Compass, Binoculars } from "lucide-react"')
a('import { Link } from "react-router-dom"')
a('import { useI18n } from "../i18n"')
a('')
a('const NAV_LINKS_KEY = ["home", "projects", "studio", "reach_us"]')
a('')
a('export default function Projects() {')
a('  const [mobileMenuOpen, setMobileMenuOpen] = useState(false)')
a('  const { t, toggleLang, lang } = useI18n()')
a('  const projects = t("projects.items")')
a('')
a('  return (')
a('    <div className="min-h-screen w-full bg-[#0a0e1a] font-geist text-white">')
a('      <nav className="sticky top-0 z-50 flex items-center justify-between px-6 py-5 md:px-12 lg:px-16 bg-black/60 backdrop-blur-xl border-b border-white/5">')
a('        <div className="flex items-center gap-8">')
a('          <Link to="/" className="text-lg font-semibold tracking-tight text-white sm:text-xl">Foldcraft</Link>')
a('          <div className="hidden md:flex items-center gap-6">')
a('            {NAV_LINKS_KEY.map((key) => (')
a('              <Link key={key} to={key === "home" ? "/" : /} className="text-sm text-white/80 hover:text-white transition-colors">')
a('                {t(
av.)}')
a('              </Link>')
a('            ))}')
a('          </div>')
a('        </div>')
a('        <div className="flex items-center gap-4">')
a('          <Link to="/reach-us">')
a('            <button className="hidden md:inline-flex rounded-lg bg-white px-5 py-2 text-sm font-medium text-black hover:scale-105 transition-transform">')
a('              {t("cta")}')
a('            </button>')
a('          </Link>')
a('          <button')
a('            onClick={toggleLang}')
a('            className="hidden md:inline-flex rounded-lg bg-white/10 px-3 py-2 text-xs text-white/80 hover:text-white hover:bg-white/20 transition-colors"')
a('            title={lang === "zh" ? "Switch to English" : "切换为中文"}')
a('          >')
a('            <Globe className="w-4 h-4" />')
a('          </button>')
a('          <button className="md:hidden active:scale-90 w-10 h-10 flex items-center justify-center" onClick={() => setMobileMenuOpen(!mobileMenuOpen)}>')
a('            {mobileMenuOpen ? <X className="w-6 h-6 text-white" /> : <Menu className="w-6 h-6 text-white" />}')
a('          </button>')
a('        </div>')
a('      </nav>')
a('')
a('      <div className={ixed inset-x-0 top-0 z-40 bg-black/[0.98] backdrop-blur-xl transition-all duration-500 ease-[cubic-bezier(0.16,1,0.3,1)] }>')
a('        <div className={lex h-full flex-col items-center justify-center px-8 transition-all duration-500 delay-100 }>')
a('          {NAV_LINKS_KEY.map((key) => (')
a('            <Link key={key} to={key === "home" ? "/" : /} className="text-3xl font-medium text-white/90 hover:text-white my-4" onClick={() => setMobileMenuOpen(false)}>')
a('              {t(
av.)}')
a('            </Link>')
a('          ))}')
a('          <Link to="/reach-us" onClick={() => setMobileMenuOpen(false)}>')
a('            <button className="mt-6 rounded-full bg-white px-8 py-3.5 text-base font-medium text-black hover:scale-105 transition-transform">')
a('              {t("cta")}')
a('            </button>')
a('          </Link>')
a('          <button')
a('            onClick={() => { toggleLang(); setMobileMenuOpen(false); }}')
a('            className="mt-4 flex items-center gap-2 text-white/60 hover:text-white transition-colors"')
a('          >')
a('            <Globe className="w-5 h-5" />')
a('            <span className="text-sm">{lang === "zh" ? "English" : "中文"}</span>')
a('          </button>')
a('        </div>')
a('      </div>')
a('')
a('      <div className="px-6 pt-16 pb-12 md:px-12 lg:px-16">')
a('        <p className="text-sm text-cyan-400/80 mb-3 tracking-wide uppercase">{t("projects.section_label")}</p>')
a('        <h1 className="text-4xl sm:text-5xl md:text-6xl font-medium leading-tight tracking-tight">')
a('          {t("projects.title").split("\\\\n").map((line, i) => (')
a('            <span key={i}>{line}{i < t("projects.title").split("\\\\n").length - 1 && <br className="hidden sm:block" />}</span>')
a('          ))}')
a('        </h1>')
a('        <p className="mt-6 max-w-lg text-base text-white/50 leading-relaxed">')
a('          {t("projects.description")}')
a('        </p>')
a('      </div>')
a('')
a('      <div className="px-6 pb-20 md:px-12 lg:px-16">')
a('        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">')
a('          {projects.map((project, i) => {')
a('            const colors = ["from-blue-600 to-cyan-500", "from-orange-500 to-amber-400", "from-emerald-600 to-teal-500", "from-indigo-600 to-purple-500", "from-rose-500 to-pink-400", "from-sky-500 to-blue-400"]')
a('            const Icons = [Waves, Fish, Globe, Anchor, Binoculars, Compass]')
a('            const Icon = Icons[i]')
a('            return (')
a('              <Link key={project.slug} to={/projects/}>')
a('                <div className="group relative rounded-xl bg-white/[0.04] border border-white/[0.06] overflow-hidden hover:bg-white/[0.07] transition-all duration-300 cursor-pointer">')
a('                  <div className={h-1 w-full bg-gradient-to-r  opacity-0 group-hover:opacity-100 transition-opacity duration-300} />')
a('                  <div className="p-6">')
a('                    <div className={w-12 h-12 rounded-lg bg-gradient-to-br  flex items-center justify-center mb-5}>')
a('                      <Icon className="w-6 h-6 text-white" />')
a('                    </div>')
a('                    <p className="text-xs text-white/40 uppercase tracking-wider mb-2">{project.tag}</p>')
a('                    <h3 className="text-lg font-medium mb-2 group-hover:text-white transition-colors">{project.title}</h3>')
a('                    <p className="text-sm text-white/50 leading-relaxed">{project.desc}</p>')
a('                    <div className="mt-5 flex items-center gap-2 text-sm text-white/60 group-hover:text-cyan-400 transition-colors">')
a('                      {t("projects.view_case_study")} <ArrowRight className="w-4 h-4 group-hover:translate-x-1 transition-transform" />')
a('                    </div>')
a('                  </div>')
a('                </div>')
a('              </Link>')
a('            )')
a('          })}')
a('        </div>')
a('      </div>')
a('    </div>')
a('  )')
a('}')

with open(filepath, 'w', encoding='utf-8') as f:
    f.write('\n'.join(L) + '\n')

print('Projects.jsx written OK, size:', os.path.getsize(filepath))
